import type { Stock, StrategyProfile } from "@/types/types";
import type { SectorId } from "@/types/types";

export const BOARD_MEETING_CYCLE_LENGTH = 5; // In days, modulo to total game days to compute the board meeting day for corporations.

export const stockSeed = [
  {
    stockId: "1",
    ticker: "ADM",
    name: "Archer-Daniels-Midland Company",
    sector: "XLP",

    initialPrice: 60,
    initialSharesOutstanding: 708333333,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.24,
    baseBeta: 0.85,

    sectorCorrelation: 0.65,
    fairValueAnchor: 60,
    raidDifficulty: 13,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 0,
  },
  {
    stockId: "2",
    ticker: "BG",
    name: "Bunge Global SA",
    sector: "XLP",

    initialPrice: 95,
    initialSharesOutstanding: 147368421,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.23,
    baseBeta: 0.7,

    sectorCorrelation: 0.57,
    fairValueAnchor: 95,
    raidDifficulty: 14,
    initialStrategyProfile: "balanced",
    boardMeetingDay: 0,
  },
  {
    stockId: "3",
    ticker: "DE",
    name: "Deere & Company",
    sector: "XLI",
    initialPrice: 295,
    initialSharesOutstanding: 355932203,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.3,
    baseBeta: 1.05,
    sectorCorrelation: 0.68,
    fairValueAnchor: 295,
    raidDifficulty: 13,
    initialStrategyProfile: "growth",
    boardMeetingDay: 0,
  },
  {
    stockId: "4",
    ticker: "AGCO",
    name: "AGCO Corporation",
    sector: "XLI",
    initialPrice: 100,
    initialSharesOutstanding: 75000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.325,
    baseBeta: 1.1,
    sectorCorrelation: 0.68,
    fairValueAnchor: 100,
    raidDifficulty: 14,
    initialStrategyProfile: "growth",
    boardMeetingDay: 0,
  },
  {
    stockId: "5",
    ticker: "MOS",
    name: "The Mosaic Company",
    sector: "XLB",
    initialPrice: 42.5,
    initialSharesOutstanding: 376470588,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.425,
    baseBeta: 1.25,
    sectorCorrelation: 0.73,
    fairValueAnchor: 42.5,
    raidDifficulty: 14,
    initialStrategyProfile: "growth",
    boardMeetingDay: 0,
  },
  {
    stockId: "6",
    ticker: "NTR",
    name: "Nutrien Ltd.",
    sector: "XLB",
    initialPrice: 67.5,
    initialSharesOutstanding: 592592593,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.32,
    baseBeta: 1,
    sectorCorrelation: 0.68,
    fairValueAnchor: 67.5,
    raidDifficulty: 14,
    initialStrategyProfile: "balanced",
    boardMeetingDay: 0,
  },
  {
    stockId: "7",
    ticker: "CTVA",
    name: "Corteva Inc.",
    sector: "XLB",
    initialPrice: 52.5,
    initialSharesOutstanding: 809523810,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.23,
    baseBeta: 0.75,
    sectorCorrelation: 0.6,
    fairValueAnchor: 52.5,
    raidDifficulty: 13,
    initialStrategyProfile: "balanced",
    boardMeetingDay: 0,
  },
  {
    stockId: "8",
    ticker: "TSN",
    name: "Tyson Foods Inc.",
    sector: "XLP",
    initialPrice: 70,
    initialSharesOutstanding: 392857143,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.25,
    baseBeta: 0.65,
    sectorCorrelation: 0.55,
    fairValueAnchor: 70,
    raidDifficulty: 14,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 0,
  },
  {
    stockId: "9",
    ticker: "CALM",
    name: "Cal-Maine Foods Inc.",
    sector: "XLP",
    initialPrice: 75,
    initialSharesOutstanding: 40000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.4,
    baseBeta: 0.2,
    sectorCorrelation: 0.33,
    fairValueAnchor: 75,
    raidDifficulty: 14,
    initialStrategyProfile: "balanced",
    boardMeetingDay: 0,
  },
  {
    stockId: "10",
    ticker: "FMC",
    name: "FMC Corporation",
    sector: "XLB",
    initialPrice: 85,
    initialSharesOutstanding: 129411765,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.35,
    baseBeta: 1,
    sectorCorrelation: 0.63,
    fairValueAnchor: 85,
    raidDifficulty: 14,
    initialStrategyProfile: "growth",
    boardMeetingDay: 0,
  },
  {
    stockId: "11",
    ticker: "XOM",
    name: "Exxon Mobil Corporation",
    sector: "XLE",
    initialPrice: 92.5,
    initialSharesOutstanding: 4054054054,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.275,
    baseBeta: 1,
    sectorCorrelation: 0.73,
    fairValueAnchor: 92.5,
    raidDifficulty: 9,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 0,
  },
  {
    stockId: "12",
    ticker: "CVX",
    name: "Chevron Corporation",
    sector: "XLE",
    initialPrice: 120,
    initialSharesOutstanding: 2166666667,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.25,
    baseBeta: 1,
    sectorCorrelation: 0.73,
    fairValueAnchor: 120,
    raidDifficulty: 11,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 0,
  },
  {
    stockId: "13",
    ticker: "COP",
    name: "ConocoPhillips",
    sector: "XLE",
    initialPrice: 80,
    initialSharesOutstanding: 1375000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.365,
    baseBeta: 1.15,
    sectorCorrelation: 0.73,
    fairValueAnchor: 80,
    raidDifficulty: 13,
    initialStrategyProfile: "growth",
    boardMeetingDay: 0,
  },
  {
    stockId: "14",
    ticker: "EOG",
    name: "EOG Resources Inc.",
    sector: "XLE",
    initialPrice: 90,
    initialSharesOutstanding: 611111111,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.365,
    baseBeta: 1.2,
    sectorCorrelation: 0.73,
    fairValueAnchor: 90,
    raidDifficulty: 13,
    initialStrategyProfile: "growth",
    boardMeetingDay: 0,
  },
  {
    stockId: "15",
    ticker: "OXY",
    name: "Occidental Petroleum Corporation",
    sector: "XLE",
    initialPrice: 44.5,
    initialSharesOutstanding: 876404494,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.475,
    baseBeta: 1.45,
    sectorCorrelation: 0.78,
    fairValueAnchor: 44.5,
    raidDifficulty: 14,
    initialStrategyProfile: "growth",
    boardMeetingDay: 0,
  },
  {
    stockId: "16",
    ticker: "SLB",
    name: "SLB",
    sector: "XLE",
    initialPrice: 40,
    initialSharesOutstanding: 1625000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.325,
    baseBeta: 1.3,
    sectorCorrelation: 0.73,
    fairValueAnchor: 40,
    raidDifficulty: 13,
    initialStrategyProfile: "growth",
    boardMeetingDay: 0,
  },
  {
    stockId: "17",
    ticker: "ENB",
    name: "Enbridge Inc.",
    sector: "XLE",
    initialPrice: 41.5,
    initialSharesOutstanding: 1807228916,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.2,
    baseBeta: 0.75,
    sectorCorrelation: 0.57,
    fairValueAnchor: 41.5,
    raidDifficulty: 13,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 1,
  },
  {
    stockId: "18",
    ticker: "KMI",
    name: "Kinder Morgan Inc.",
    sector: "XLE",
    initialPrice: 20,
    initialSharesOutstanding: 1875000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.22,
    baseBeta: 0.85,
    sectorCorrelation: 0.57,
    fairValueAnchor: 20,
    raidDifficulty: 14,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 1,
  },
  {
    stockId: "19",
    ticker: "NEE",
    name: "NextEra Energy Inc.",
    sector: "XLU",
    initialPrice: 70,
    initialSharesOutstanding: 1714285714,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.2,
    baseBeta: 0.6,
    sectorCorrelation: 0.48,
    fairValueAnchor: 70,
    raidDifficulty: 13,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 1,
  },
  {
    stockId: "20",
    ticker: "DUK",
    name: "Duke Energy Corporation",
    sector: "XLU",
    initialPrice: 95,
    initialSharesOutstanding: 710526316,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.17,
    baseBeta: 0.45,
    sectorCorrelation: 0.45,
    fairValueAnchor: 95,
    raidDifficulty: 13,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 1,
  },
  {
    stockId: "21",
    ticker: "CAT",
    name: "Caterpillar Inc.",
    sector: "XLI",
    initialPrice: 245,
    initialSharesOutstanding: 510204082,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.285,
    baseBeta: 1.1,
    sectorCorrelation: 0.68,
    fairValueAnchor: 245,
    raidDifficulty: 12,
    initialStrategyProfile: "balanced",
    boardMeetingDay: 1,
  },
  {
    stockId: "22",
    ticker: "GE",
    name: "GE Aerospace",
    sector: "XLI",
    initialPrice: 132.5,
    initialSharesOutstanding: 1056603774,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.345,
    baseBeta: 1.15,
    sectorCorrelation: 0.68,
    fairValueAnchor: 132.5,
    raidDifficulty: 12,
    initialStrategyProfile: "growth",
    boardMeetingDay: 1,
  },
  {
    stockId: "23",
    ticker: "HON",
    name: "Honeywell International Inc.",
    sector: "XLI",
    initialPrice: 170,
    initialSharesOutstanding: 705882353,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.23,
    baseBeta: 0.85,
    sectorCorrelation: 0.63,
    fairValueAnchor: 170,
    raidDifficulty: 13,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 1,
  },
  {
    stockId: "24",
    ticker: "ETN",
    name: "Eaton Corporation plc",
    sector: "XLI",
    initialPrice: 215,
    initialSharesOutstanding: 441860465,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.285,
    baseBeta: 1.05,
    sectorCorrelation: 0.68,
    fairValueAnchor: 215,
    raidDifficulty: 13,
    initialStrategyProfile: "growth",
    boardMeetingDay: 1,
  },
  {
    stockId: "25",
    ticker: "EMR",
    name: "Emerson Electric Co.",
    sector: "XLI",
    initialPrice: 80,
    initialSharesOutstanding: 593750000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.24,
    baseBeta: 0.95,
    sectorCorrelation: 0.63,
    fairValueAnchor: 80,
    raidDifficulty: 13,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 1,
  },
  {
    stockId: "26",
    ticker: "PH",
    name: "Parker-Hannifin Corporation",
    sector: "XLI",
    initialPrice: 390,
    initialSharesOutstanding: 147435897,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.26,
    baseBeta: 1.1,
    sectorCorrelation: 0.68,
    fairValueAnchor: 390,
    raidDifficulty: 13,
    initialStrategyProfile: "balanced",
    boardMeetingDay: 1,
  },
  {
    stockId: "27",
    ticker: "ITW",
    name: "Illinois Tool Works Inc.",
    sector: "XLI",
    initialPrice: 210,
    initialSharesOutstanding: 333333333,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.225,
    baseBeta: 0.85,
    sectorCorrelation: 0.6,
    fairValueAnchor: 210,
    raidDifficulty: 13,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 1,
  },
  {
    stockId: "28",
    ticker: "CMI",
    name: "Cummins Inc.",
    sector: "XLI",
    initialPrice: 220,
    initialSharesOutstanding: 125000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.3,
    baseBeta: 1.2,
    sectorCorrelation: 0.68,
    fairValueAnchor: 220,
    raidDifficulty: 14,
    initialStrategyProfile: "growth",
    boardMeetingDay: 1,
  },
  {
    stockId: "29",
    ticker: "MMM",
    name: "3M Company",
    sector: "XLI",
    initialPrice: 160,
    initialSharesOutstanding: 562500000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.265,
    baseBeta: 0.95,
    sectorCorrelation: 0.63,
    fairValueAnchor: 160,
    raidDifficulty: 13,
    initialStrategyProfile: "balanced",
    boardMeetingDay: 1,
  },
  {
    stockId: "30",
    ticker: "RTX",
    name: "RTX Corporation",
    sector: "XLI",
    initialPrice: 95,
    initialSharesOutstanding: 1263157895,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.23,
    baseBeta: 0.85,
    sectorCorrelation: 0.63,
    fairValueAnchor: 95,
    raidDifficulty: 13,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 1,
  },
  {
    stockId: "31",
    ticker: "JNJ",
    name: "Johnson & Johnson",
    sector: "XLV",
    initialPrice: 160,
    initialSharesOutstanding: 2500000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.16,
    baseBeta: 0.55,
    sectorCorrelation: 0.45,
    fairValueAnchor: 160,
    raidDifficulty: 9,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 1,
  },
  {
    stockId: "32",
    ticker: "PFE",
    name: "Pfizer Inc.",
    sector: "XLV",
    initialPrice: 42.5,
    initialSharesOutstanding: 5647058824,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.22,
    baseBeta: 0.7,
    sectorCorrelation: 0.53,
    fairValueAnchor: 42.5,
    raidDifficulty: 11,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 1,
  },
  {
    stockId: "33",
    ticker: "MRK",
    name: "Merck & Co. Inc.",
    sector: "XLV",
    initialPrice: 92.5,
    initialSharesOutstanding: 2702702703,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.2,
    baseBeta: 0.6,
    sectorCorrelation: 0.53,
    fairValueAnchor: 92.5,
    raidDifficulty: 11,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 2,
  },
  {
    stockId: "34",
    ticker: "ABBV",
    name: "AbbVie Inc.",
    sector: "XLV",
    initialPrice: 135,
    initialSharesOutstanding: 1592592593,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.22,
    baseBeta: 0.7,
    sectorCorrelation: 0.53,
    fairValueAnchor: 135,
    raidDifficulty: 11,
    initialStrategyProfile: "balanced",
    boardMeetingDay: 2,
  },
  {
    stockId: "35",
    ticker: "AMGN",
    name: "Amgen Inc.",
    sector: "XLV",
    initialPrice: 260,
    initialSharesOutstanding: 519230769,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.2,
    baseBeta: 0.6,
    sectorCorrelation: 0.53,
    fairValueAnchor: 260,
    raidDifficulty: 12,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 2,
  },
  {
    stockId: "36",
    ticker: "GILD",
    name: "Gilead Sciences Inc.",
    sector: "XLV",
    initialPrice: 72.5,
    initialSharesOutstanding: 1379310345,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.195,
    baseBeta: 0.55,
    sectorCorrelation: 0.48,
    fairValueAnchor: 72.5,
    raidDifficulty: 13,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 2,
  },
  {
    stockId: "37",
    ticker: "BMY",
    name: "Bristol Myers Squibb Company",
    sector: "XLV",
    initialPrice: 60,
    initialSharesOutstanding: 2000000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.21,
    baseBeta: 0.6,
    sectorCorrelation: 0.53,
    fairValueAnchor: 60,
    raidDifficulty: 13,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 2,
  },
  {
    stockId: "38",
    ticker: "MDT",
    name: "Medtronic plc",
    sector: "XLV",
    initialPrice: 100,
    initialSharesOutstanding: 1300000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.2,
    baseBeta: 0.7,
    sectorCorrelation: 0.53,
    fairValueAnchor: 100,
    raidDifficulty: 12,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 2,
  },
  {
    stockId: "39",
    ticker: "ISRG",
    name: "Intuitive Surgical Inc.",
    sector: "XLV",
    initialPrice: 107.5,
    initialSharesOutstanding: 1023255814,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.325,
    baseBeta: 1.1,
    sectorCorrelation: 0.57,
    fairValueAnchor: 107.5,
    raidDifficulty: 13,
    initialStrategyProfile: "growth",
    boardMeetingDay: 2,
  },
  {
    stockId: "40",
    ticker: "SYK",
    name: "Stryker Corporation",
    sector: "XLV",
    initialPrice: 280,
    initialSharesOutstanding: 392857143,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.23,
    baseBeta: 0.85,
    sectorCorrelation: 0.57,
    fairValueAnchor: 280,
    raidDifficulty: 13,
    initialStrategyProfile: "growth",
    boardMeetingDay: 2,
  },
  {
    stockId: "41",
    ticker: "JPM",
    name: "JPMorgan Chase & Co.",
    sector: "XLF",
    initialPrice: 177.5,
    initialSharesOutstanding: 2478873239,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.275,
    baseBeta: 1.1,
    sectorCorrelation: 0.68,
    fairValueAnchor: 177.5,
    raidDifficulty: 9,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 2,
  },
  {
    stockId: "42",
    ticker: "BAC",
    name: "Bank of America Corporation",
    sector: "XLF",
    initialPrice: 37.5,
    initialSharesOutstanding: 7333333333,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.325,
    baseBeta: 1.35,
    sectorCorrelation: 0.73,
    fairValueAnchor: 37.5,
    raidDifficulty: 11,
    initialStrategyProfile: "growth",
    boardMeetingDay: 2,
  },
  {
    stockId: "43",
    ticker: "WFC",
    name: "Wells Fargo & Company",
    sector: "XLF",
    initialPrice: 43.5,
    initialSharesOutstanding: 4022988506,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.32,
    baseBeta: 1.25,
    sectorCorrelation: 0.73,
    fairValueAnchor: 43.5,
    raidDifficulty: 12,
    initialStrategyProfile: "growth",
    boardMeetingDay: 2,
  },
  {
    stockId: "44",
    ticker: "C",
    name: "Citigroup Inc.",
    sector: "XLF",
    initialPrice: 60,
    initialSharesOutstanding: 2083333333,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.365,
    baseBeta: 1.5,
    sectorCorrelation: 0.73,
    fairValueAnchor: 60,
    raidDifficulty: 12,
    initialStrategyProfile: "growth",
    boardMeetingDay: 2,
  },
  {
    stockId: "45",
    ticker: "GS",
    name: "The Goldman Sachs Group Inc.",
    sector: "XLF",
    initialPrice: 420,
    initialSharesOutstanding: 321428571,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.3,
    baseBeta: 1.3,
    sectorCorrelation: 0.68,
    fairValueAnchor: 420,
    raidDifficulty: 12,
    initialStrategyProfile: "growth",
    boardMeetingDay: 2,
  },
  {
    stockId: "46",
    ticker: "MS",
    name: "Morgan Stanley",
    sector: "XLF",
    initialPrice: 87.5,
    initialSharesOutstanding: 1600000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.32,
    baseBeta: 1.35,
    sectorCorrelation: 0.68,
    fairValueAnchor: 87.5,
    raidDifficulty: 12,
    initialStrategyProfile: "growth",
    boardMeetingDay: 2,
  },
  {
    stockId: "47",
    ticker: "AXP",
    name: "American Express Company",
    sector: "XLF",
    initialPrice: 192.5,
    initialSharesOutstanding: 753246753,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.275,
    baseBeta: 1.2,
    sectorCorrelation: 0.63,
    fairValueAnchor: 192.5,
    raidDifficulty: 12,
    initialStrategyProfile: "growth",
    boardMeetingDay: 2,
  },
  {
    stockId: "48",
    ticker: "BLK",
    name: "BlackRock Inc.",
    sector: "XLF",
    initialPrice: 700,
    initialSharesOutstanding: 157142857,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.275,
    baseBeta: 1.25,
    sectorCorrelation: 0.63,
    fairValueAnchor: 700,
    raidDifficulty: 13,
    initialStrategyProfile: "growth",
    boardMeetingDay: 2,
  },
  {
    stockId: "49",
    ticker: "SCHW",
    name: "The Charles Schwab Corporation",
    sector: "XLF",
    initialPrice: 57.5,
    initialSharesOutstanding: 1913043478,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.35,
    baseBeta: 1.3,
    sectorCorrelation: 0.68,
    fairValueAnchor: 57.5,
    raidDifficulty: 13,
    initialStrategyProfile: "growth",
    boardMeetingDay: 3,
  },
  {
    stockId: "50",
    ticker: "USB",
    name: "U.S. Bancorp",
    sector: "XLF",
    initialPrice: 50,
    initialSharesOutstanding: 1550000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.275,
    baseBeta: 1.1,
    sectorCorrelation: 0.63,
    fairValueAnchor: 50,
    raidDifficulty: 13,
    initialStrategyProfile: "balanced",
    boardMeetingDay: 3,
  },
  {
    stockId: "51",
    ticker: "WMT",
    name: "Walmart Inc.",
    sector: "XLY",
    initialPrice: 70,
    initialSharesOutstanding: 8571428571,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.17,
    baseBeta: 0.55,
    sectorCorrelation: 0.48,
    fairValueAnchor: 70,
    raidDifficulty: 7,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 3,
  },
  {
    stockId: "52",
    ticker: "COST",
    name: "Costco Wholesale Corporation",
    sector: "XLY",
    initialPrice: 72.5,
    initialSharesOutstanding: 3793103448,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.23,
    baseBeta: 0.75,
    sectorCorrelation: 0.53,
    fairValueAnchor: 72.5,
    raidDifficulty: 11,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 3,
  },
  {
    stockId: "53",
    ticker: "PG",
    name: "The Procter & Gamble Company",
    sector: "XLP",
    initialPrice: 125,
    initialSharesOutstanding: 2400000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.16,
    baseBeta: 0.5,
    sectorCorrelation: 0.45,
    fairValueAnchor: 125,
    raidDifficulty: 10,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 3,
  },
  {
    stockId: "54",
    ticker: "KO",
    name: "The Coca-Cola Company",
    sector: "XLP",
    initialPrice: 55,
    initialSharesOutstanding: 4545454545,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.16,
    baseBeta: 0.45,
    sectorCorrelation: 0.45,
    fairValueAnchor: 55,
    raidDifficulty: 11,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 3,
  },
  {
    stockId: "55",
    ticker: "PEP",
    name: "PepsiCo Inc.",
    sector: "XLP",
    initialPrice: 142.5,
    initialSharesOutstanding: 1684210526,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.18,
    baseBeta: 0.6,
    sectorCorrelation: 0.48,
    fairValueAnchor: 142.5,
    raidDifficulty: 11,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 3,
  },
  {
    stockId: "56",
    ticker: "MCD",
    name: "McDonald's Corporation",
    sector: "XLY",
    initialPrice: 217.5,
    initialSharesOutstanding: 827586207,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.205,
    baseBeta: 0.7,
    sectorCorrelation: 0.53,
    fairValueAnchor: 217.5,
    raidDifficulty: 12,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 3,
  },
  {
    stockId: "57",
    ticker: "NKE",
    name: "Nike Inc.",
    sector: "XLY",
    initialPrice: 115,
    initialSharesOutstanding: 1608695652,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.275,
    baseBeta: 0.9,
    sectorCorrelation: 0.57,
    fairValueAnchor: 115,
    raidDifficulty: 12,
    initialStrategyProfile: "growth",
    boardMeetingDay: 3,
  },
  {
    stockId: "58",
    ticker: "TGT",
    name: "Target Corporation",
    sector: "XLY",
    initialPrice: 157.5,
    initialSharesOutstanding: 523809524,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.275,
    baseBeta: 0.9,
    sectorCorrelation: 0.57,
    fairValueAnchor: 157.5,
    raidDifficulty: 13,
    initialStrategyProfile: "growth",
    boardMeetingDay: 3,
  },
  {
    stockId: "59",
    ticker: "HD",
    name: "The Home Depot Inc.",
    sector: "XLY",
    initialPrice: 255,
    initialSharesOutstanding: 1176470588,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.24,
    baseBeta: 0.95,
    sectorCorrelation: 0.57,
    fairValueAnchor: 255,
    raidDifficulty: 10,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 3,
  },
  {
    stockId: "60",
    ticker: "LOW",
    name: "Lowe's Companies Inc.",
    sector: "XLY",
    initialPrice: 170,
    initialSharesOutstanding: 676470588,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.26,
    baseBeta: 1.05,
    sectorCorrelation: 0.57,
    fairValueAnchor: 170,
    raidDifficulty: 13,
    initialStrategyProfile: "growth",
    boardMeetingDay: 3,
  },
  {
    stockId: "61",
    ticker: "MSFT",
    name: "Microsoft Corporation",
    sector: "XLK",
    initialPrice: 267.5,
    initialSharesOutstanding: 7102803738,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.25,
    baseBeta: 0.95,
    sectorCorrelation: 0.68,
    fairValueAnchor: 267.5,
    raidDifficulty: 5,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 3,
  },
  {
    stockId: "62",
    ticker: "AAPL",
    name: "Apple Inc.",
    sector: "XLK",
    initialPrice: 140,
    initialSharesOutstanding: 14285714286,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.3,
    baseBeta: 1.2,
    sectorCorrelation: 0.68,
    fairValueAnchor: 140,
    raidDifficulty: 5,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 3,
  },
  {
    stockId: "63",
    ticker: "NVDA",
    name: "NVIDIA Corporation",
    sector: "XLK",
    initialPrice: 91.5,
    initialSharesOutstanding: 21912568306,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.575,
    baseBeta: 1.6,
    sectorCorrelation: 0.75,
    fairValueAnchor: 91.5,
    raidDifficulty: 5,
    initialStrategyProfile: "growth",
    boardMeetingDay: 3,
  },
  {
    stockId: "64",
    ticker: "AVGO",
    name: "Broadcom Inc.",
    sector: "XLK",
    initialPrice: 132.5,
    initialSharesOutstanding: 4830188679,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.35,
    baseBeta: 1.2,
    sectorCorrelation: 0.68,
    fairValueAnchor: 132.5,
    raidDifficulty: 6,
    initialStrategyProfile: "growth",
    boardMeetingDay: 3,
  },
  {
    stockId: "65",
    ticker: "ORCL",
    name: "Oracle Corporation",
    sector: "XLK",
    initialPrice: 127.5,
    initialSharesOutstanding: 2823529412,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.24,
    baseBeta: 1.05,
    sectorCorrelation: 0.63,
    fairValueAnchor: 127.5,
    raidDifficulty: 10,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 4,
  },
  {
    stockId: "66",
    ticker: "CRM",
    name: "Salesforce Inc.",
    sector: "XLK",
    initialPrice: 185,
    initialSharesOutstanding: 1054054054,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.32,
    baseBeta: 1.2,
    sectorCorrelation: 0.68,
    fairValueAnchor: 185,
    raidDifficulty: 12,
    initialStrategyProfile: "growth",
    boardMeetingDay: 4,
  },
  {
    stockId: "67",
    ticker: "ADBE",
    name: "Adobe Inc.",
    sector: "XLK",
    initialPrice: 450,
    initialSharesOutstanding: 500000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.285,
    baseBeta: 1.15,
    sectorCorrelation: 0.63,
    fairValueAnchor: 450,
    raidDifficulty: 11,
    initialStrategyProfile: "growth",
    boardMeetingDay: 4,
  },
  {
    stockId: "68",
    ticker: "AMD",
    name: "Advanced Micro Devices Inc.",
    sector: "XLK",
    initialPrice: 111,
    initialSharesOutstanding: 1824324324,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.525,
    baseBeta: 1.85,
    sectorCorrelation: 0.75,
    fairValueAnchor: 111,
    raidDifficulty: 11,
    initialStrategyProfile: "growth",
    boardMeetingDay: 4,
  },
  {
    stockId: "69",
    ticker: "INTC",
    name: "Intel Corporation",
    sector: "XLK",
    initialPrice: 44,
    initialSharesOutstanding: 5113636364,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.3,
    baseBeta: 0.95,
    sectorCorrelation: 0.63,
    fairValueAnchor: 44,
    raidDifficulty: 11,
    initialStrategyProfile: "balanced",
    boardMeetingDay: 4,
  },
  {
    stockId: "70",
    ticker: "CSCO",
    name: "Cisco Systems Inc.",
    sector: "XLK",
    initialPrice: 50,
    initialSharesOutstanding: 3700000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.205,
    baseBeta: 0.85,
    sectorCorrelation: 0.57,
    fairValueAnchor: 50,
    raidDifficulty: 12,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 4,
  },
  {
    stockId: "71",
    ticker: "UPS",
    name: "United Parcel Service Inc.",
    sector: "XLI",
    initialPrice: 145,
    initialSharesOutstanding: 965517241,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.24,
    baseBeta: 0.95,
    sectorCorrelation: 0.63,
    fairValueAnchor: 145,
    raidDifficulty: 12,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 4,
  },
  {
    stockId: "72",
    ticker: "FDX",
    name: "FedEx Corporation",
    sector: "XLI",
    initialPrice: 200,
    initialSharesOutstanding: 350000000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.3,
    baseBeta: 1.2,
    sectorCorrelation: 0.68,
    fairValueAnchor: 200,
    raidDifficulty: 13,
    initialStrategyProfile: "growth",
    boardMeetingDay: 4,
  },
  {
    stockId: "73",
    ticker: "UNP",
    name: "Union Pacific Corporation",
    sector: "XLI",
    initialPrice: 172.5,
    initialSharesOutstanding: 811594203,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.23,
    baseBeta: 1.05,
    sectorCorrelation: 0.63,
    fairValueAnchor: 172.5,
    raidDifficulty: 12,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 4,
  },
  {
    stockId: "74",
    ticker: "CSX",
    name: "CSX Corporation",
    sector: "XLI",
    initialPrice: 27.5,
    initialSharesOutstanding: 2545454545,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.24,
    baseBeta: 1,
    sectorCorrelation: 0.63,
    fairValueAnchor: 27.5,
    raidDifficulty: 13,
    initialStrategyProfile: "balanced",
    boardMeetingDay: 4,
  },
  {
    stockId: "75",
    ticker: "NSC",
    name: "Norfolk Southern Corporation",
    sector: "XLI",
    initialPrice: 225,
    initialSharesOutstanding: 233333333,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.24,
    baseBeta: 1,
    sectorCorrelation: 0.63,
    fairValueAnchor: 225,
    raidDifficulty: 13,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 4,
  },
  {
    stockId: "76",
    ticker: "JBHT",
    name: "J.B. Hunt Transport Services Inc.",
    sector: "XLI",
    initialPrice: 145,
    initialSharesOutstanding: 127586207,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.285,
    baseBeta: 1.1,
    sectorCorrelation: 0.68,
    fairValueAnchor: 145,
    raidDifficulty: 14,
    initialStrategyProfile: "growth",
    boardMeetingDay: 4,
  },
  {
    stockId: "77",
    ticker: "ODFL",
    name: "Old Dominion Freight Line Inc.",
    sector: "XLI",
    initialPrice: 137.5,
    initialSharesOutstanding: 218181818,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.325,
    baseBeta: 1.2,
    sectorCorrelation: 0.68,
    fairValueAnchor: 137.5,
    raidDifficulty: 14,
    initialStrategyProfile: "growth",
    boardMeetingDay: 4,
  },
  {
    stockId: "78",
    ticker: "EXPD",
    name: "Expeditors International of Washington Inc.",
    sector: "XLI",
    initialPrice: 110,
    initialSharesOutstanding: 181818182,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.23,
    baseBeta: 0.95,
    sectorCorrelation: 0.57,
    fairValueAnchor: 110,
    raidDifficulty: 14,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 4,
  },
  {
    stockId: "79",
    ticker: "CHRW",
    name: "C.H. Robinson Worldwide Inc.",
    sector: "XLI",
    initialPrice: 95,
    initialSharesOutstanding: 147368421,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.205,
    baseBeta: 0.75,
    sectorCorrelation: 0.55,
    fairValueAnchor: 95,
    raidDifficulty: 14,
    initialStrategyProfile: "blue-chip",
    boardMeetingDay: 4,
  },
  {
    stockId: "80",
    ticker: "XPO",
    name: "XPO Inc.",
    sector: "XLI",
    initialPrice: 80,
    initialSharesOutstanding: 131250000,
    baseRegimeDrift: 0.01,
    baseVolatility: 0.425,
    baseBeta: 1.5,
    sectorCorrelation: 0.73,
    fairValueAnchor: 80,
    raidDifficulty: 14,
    initialStrategyProfile: "growth",
    boardMeetingDay: 4,
  },
];

export const Stocks: Stock[] = stockSeed.map((stock) => ({
  stockId: stock.stockId,
  ticker: stock.ticker,
  name: stock.name,
  sector: stock.sector as SectorId,
  initialPrice: stock.initialPrice,
  initialSharesOutstanding: stock.initialSharesOutstanding,
  baseRegimeDrift: stock.baseRegimeDrift,
  baseVolatility: stock.baseVolatility,
  baseBeta: stock.baseBeta,
  initialStrategyProfile: stock.initialStrategyProfile as StrategyProfile,
  sectorCorrelation: stock.sectorCorrelation,
  fairValueAnchor: stock.fairValueAnchor,
  raidDifficulty: stock.raidDifficulty,
  boardMeetingDay: stock.boardMeetingDay,
  currentPrice: stock.initialPrice,
  currentSharesOutstanding: stock.initialSharesOutstanding,
  currentRegimeDrift: stock.baseRegimeDrift,
  currentVolatility: stock.baseVolatility,
  currentBeta: stock.baseBeta,
  lastShock: 0,
  currentStrategyProfile: stock.initialStrategyProfile as StrategyProfile,
  ownedShares: 0,
  controlLevel: "none",
  extractionRate: 0,
  priceHistory: [],
}));