import type { ServiceJobId, TechJobId, FinanceJobId, JobDef, CareerState } from "@/types/types";

export const CAREER_TRACK_IDS = [
  "service",
  "tech",
  "finance",
];

export const careerStartState: CareerState = {
  careerTrack: "service",
  titleId: "burgerFlipper",
  queuedCareerTrack: null,
  queuedTitleId: null,
  collegeLevel: 0,
  collegeXp: 0,
  collegeActive: false,
  xpByTrack: { service: 0, tech: 0, finance: 0 },
  wagePerDay: 0,
  financeCommissionRate: 0,
};

export const serviceJobs: Record<ServiceJobId, JobDef> = {
  burgerFlipper: {
    careerTrack: "service",
    jobId: "burgerFlipper",
    title: "Burger Flipper",
    collegeLevelRequirement: 0,
    xpLevelRequirement: 0,
    wageLevelMult: 1,
    wageLevelBase: 1,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
  },
  supervisor: {
    careerTrack: "service",
    jobId: "supervisor",
    title: "Supervisor",
    collegeLevelRequirement: 15,
    xpLevelRequirement: 10,
    wageLevelMult: 1.5,
    wageLevelBase: 1,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
  },
  storeManager: {
    careerTrack: "service",
    jobId: "storeManager",
    title: "Store Manager",
    collegeLevelRequirement: 15,
    xpLevelRequirement: 20,
    wageLevelMult: 2.0,
    wageLevelBase: 1,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
  },
  districtManager: {
    careerTrack: "service",
    jobId: "districtManager",
    title: "District Manager",
    collegeLevelRequirement: 15,
    xpLevelRequirement: 30,
    wageLevelMult: 3.0,
    wageLevelBase: 1,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
  },
  regionalExecutive: {
    careerTrack: "service",
    jobId: "regionalExecutive",
    title: "Regional Executive",
    collegeLevelRequirement: 15,
    xpLevelRequirement: 40,
    wageLevelMult: 5,
    wageLevelBase: 1,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
  },
  vp: {
    careerTrack: "service",
    jobId: "vp",
    title: "VP",
    collegeLevelRequirement: 25,
    xpLevelRequirement: 50,
    wageLevelMult: 7.5,
    wageLevelBase: 1,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
  },
  ceo: {
    careerTrack: "service",
    jobId: "ceo",
    title: "CEO",
    collegeLevelRequirement: 25,
    xpLevelRequirement: 60,
    wageLevelMult: 12,
    wageLevelBase: 1,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
  },
};

export const techJobs: Record<TechJobId, JobDef> = {
  unpaidIntern: {
    careerTrack: "tech",
    jobId: "unpaidIntern",
    title: "Unpaid Intern",
    collegeLevelRequirement: 0,
    xpLevelRequirement: 0,
    wageLevelMult: 0,
    wageLevelBase: 0,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
  },
  juniorITDev: {
    careerTrack: "tech",
    jobId: "juniorITDev",
    title: "Junior IT/Dev",
    collegeLevelRequirement: 25,
    xpLevelRequirement: 10,
    wageLevelMult: 0.8,
    wageLevelBase: 10,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
  },
  engineer: {
    careerTrack: "tech",
    jobId: "engineer",
    title: "Engineer",
    collegeLevelRequirement: 25,
    xpLevelRequirement: 20,
    wageLevelMult: 1.2,
    wageLevelBase: 10,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
  },
  seniorEngineer: {
    careerTrack: "tech",
    jobId: "seniorEngineer",
    title: "Senior Engineer",
    collegeLevelRequirement: 25,
    xpLevelRequirement: 30,
    wageLevelMult: 18,
    wageLevelBase: 10,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
  },
  staffPrincipal: {
    careerTrack: "tech",
    jobId: "staffPrincipal",
    title: "Staff/Principal",
    collegeLevelRequirement: 50,
    xpLevelRequirement: 40,
    wageLevelMult: 2.7,
    wageLevelBase: 10,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
  },
  vpEngineering: {
    careerTrack: "tech",
    jobId: "vpEngineering",
    title: "VP Engineering",
    collegeLevelRequirement: 50,
    xpLevelRequirement: 50,
    wageLevelMult: 40,
    wageLevelBase: 10,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
    },
  ceo: {
    careerTrack: "tech",
    jobId: "ceo",
    title: "CEO",
    collegeLevelRequirement: 50,
    xpLevelRequirement: 60,
    wageLevelMult: 6.0,
    wageLevelBase: 10,
    xpLevelProgress: 0,
    financeCommissionRate: 0,
  },
};

export const financeJobs: Record<FinanceJobId, JobDef> = {
  unpaidIntern: {
    careerTrack: "finance",
    jobId: "unpaidIntern",
    title: "Unpaid Intern",
    collegeLevelRequirement: 0,
    xpLevelRequirement: 0,
    xpLevelProgress: 0,
    wageLevelMult: 0,
    wageLevelBase: 0,
    financeCommissionRate: 0,
  },
  analyst: {
    careerTrack: "finance",
    jobId: "analyst",
    title: "Analyst",
    collegeLevelRequirement: 40,
    xpLevelRequirement: 10,
    xpLevelProgress: 0,
    wageLevelMult: 1,
    wageLevelBase: 2,
    financeCommissionRate: 0.02,
  },
  associate: {
    careerTrack: "finance",
    jobId: "associate",
    title: "Associate",
    collegeLevelRequirement: 40,
    xpLevelRequirement: 20,
    xpLevelProgress: 0,
    wageLevelMult: 1.4,
    wageLevelBase: 2,
    financeCommissionRate: 0.03,
  },
  manager: {
    careerTrack: "finance",
    jobId: "manager",
    title: "Manager",
    collegeLevelRequirement: 40,
    xpLevelRequirement: 30,
    xpLevelProgress: 0,
    wageLevelMult: 2.0,
    wageLevelBase: 2,
    financeCommissionRate: 0.04,
  },
  director: {
    careerTrack: "finance",
    jobId: "director",
    title: "Director",
    collegeLevelRequirement: 40,
    xpLevelRequirement: 40,
    xpLevelProgress: 0,
    wageLevelMult: 2.8,
    wageLevelBase: 2,
    financeCommissionRate: 0.06,
  },
  vp: {
    careerTrack: "finance",
    jobId: "vp",
    title: "VP",
    collegeLevelRequirement: 40,
    xpLevelRequirement: 50,
    xpLevelProgress: 0,
    wageLevelMult: 4.0,
    wageLevelBase: 2,
    financeCommissionRate: 0.10,
  },
  cfo: {
    careerTrack: "finance",
    jobId: "cfo",
    title: "CFO",
    collegeLevelRequirement: 40,
    xpLevelRequirement: 60,
    xpLevelProgress: 0,
    wageLevelMult: 5.5,
    wageLevelBase: 2,
    financeCommissionRate: 0.12,
  },
  ceo: {
    careerTrack: "finance",
    jobId: "ceo",
    title: "CEO",
    collegeLevelRequirement: 40,
    xpLevelRequirement: 60,
    xpLevelProgress: 0,
    wageLevelMult: 8.0,
    wageLevelBase: 2,
    financeCommissionRate: 0.15,
  },
};

