import type { NewsItem } from "@/types/types";

export const newsItems: NewsItem[] = [
  {
    newsId: "1",
    title: "Apple Inc. announces new product",
    description: "Apple Inc. announces new product",
    date: "2026-01-01",
    category: "Technology",
    body: "Apple Inc. announces new product",
    isRead: false,
  },
  {
    newsId: "2",
    title: "Google Inc. announces new product",
    description: "Google Inc. announces new product",
    date: "2026-01-01",
    category: "Technology",
    body: "Google Inc. announces new product",
    isRead: false,
  },
  {
    newsId: "3",
    title: "Microsoft Corporation announces new product",
    description: "Microsoft Corporation announces new product",
    date: "2026-01-01",
    category: "Technology",
    body: "Microsoft Corporation announces new product",
    isRead: false,
  },
  {
    newsId: "4",
    title: "Amazon.com Inc. announces new product",
    description: "Amazon.com Inc. announces new product",
    date: "2026-01-01",
    category: "Technology",
    body: "Amazon.com Inc. announces new product",
    isRead: false,
  },
  {
    newsId: "5",
    title: "Tesla Inc. announces new product",
    description: "Tesla Inc. announces new product",
    date: "2026-01-01",
    category: "Technology",
    body: "Tesla Inc. announces new product",
    isRead: false,
  },
  {
    newsId: "6",
    title: "Meta Platforms Inc. announces new product",
    description: "Meta Platforms Inc. announces new product",
    date: "2026-01-01",
    category: "Technology",
    body: "Meta Platforms Inc. announces new product",
    isRead: false,
  },
  {
    newsId: "7",
    title: "NVIDIA Corporation announces new product",
    description: "NVIDIA Corporation announces new product",
    date: "2026-01-01",
    category: "Technology",
    body: "NVIDIA Corporation announces new product",
    isRead: false,
  },
  {
    newsId: "8",
    title: "Intel Corporation announces new product",
    description: "Intel Corporation announces new product",
    date: "2026-01-01",
    category: "Technology",
    body: "Intel Corporation announces new product",
    isRead: false,
  },
  {
    newsId: "9",
    title: "AMD Corporation announces new product",
    description: "AMD Corporation announces new product",
    date: "2026-01-01",
    category: "Technology",
    body: "AMD Corporation announces new product",
    isRead: false,
  },
  {
    newsId: "10",
    title: "ARM Holdings announces new product",
    description: "ARM Holdings announces new product",
    date: "2026-01-01",
    category: "Technology",
    body: "ARM Holdings announces new product",
    isRead: false,
  },
  {
    newsId: "11",
    title: "Broadcom Inc. announces new product",
    description: "Broadcom Inc. announces new product",
    date: "2026-01-01",
    category: "Technology",
    body: "Broadcom Inc. announces new product",
    isRead: false,
  },
  {
    newsId: "12",
    title: "Oracle Corporation announces new product",
    description: "Oracle Corporation announces new product",
    date: "2026-01-01",
    category: "Technology",
    body: "Oracle Corporation announces new product",
    isRead: false,
  },
];
